# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('0', 'Status 0'), ('1', 'Status 1'), ('2', 'Status 2'), ('3', 'Status 3'), ('4', 'Status 4'), ('5', 'Status 5'), ('6', 'Status 6'), ('7', 'Status 7'), ('8', 'Status 8'), ('9', 'Status 9'), ('10', 'Status 10'), ('11', 'Status 11'), ('12', 'Status 12'), ('13', 'Status 13')], default='0', max_length=5)),
                ('datetime', models.DateTimeField(null=True)),
                ('external_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='myapp.MyModel')),
            ],
        ),
    ]
